### ISSUE TITLE
npm module out of date

### ISSUE THREAD

**Issue by nboltn** [jz222/logowl-adapter-browser#9]
npm module seems out of date https://www.npmjs.com/package/@logowl/adapter-nodejs

**Comment by jz222** [comment]
What do you mean by out of date? What's the issue?

**Comment by nboltn** [comment]
well the last version on npm is `2.0.3`, while the actual latest should be `2.3.0`

**Comment by jz222** [comment]
The package you referenced ([https://www.npmjs.com/package/@logowl/adapter-nodejs](https://www.npmjs.com/package/@logowl/adapter-nodejs)) is the NodeJS adapter. The latest version of the NodeJS adapter is indeed `2.0.3`. You can find its repository [here](https://github.com/jz222/logowl-adapter-nodejs).

This repository contains the code for the browser adapter, whose latest version is currently `2.3.0`. You can find the NPM package for the browser adapter [here](https://www.npmjs.com/package/@logowl/adapter-browser).

If you want to check out all official adapters available, please refer this [this](https://www.npmjs.com/settings/logowl/packages) link.

**Comment by nboltn** [comment]
Adding this code:

```javascript
const logowl = require('@logowl/adapter-nodejs');
logowl.init({ ticket: 'xxxxxx' });
```

results in:

![logowl](https://user-images.githubusercontent.com/857940/85944435-6b3ca180-b8d2-11ea-926e-e826ce12d506.PNG)

**Comment by jz222** [comment]
The NodeJS adapter is, as the name says, for NodeJS applications such as Express servers. If you want to track errors in your React app, please use the browser adapter. You can find the related documentation [here](https://github.com/jz222/logowl-adapter-browser).
